import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/Footer.tsx
import { useEffect, useState } from "react";
import Container from "react-bootstrap/Container";
import { Link } from "react-router-dom";
const InstaIcon = () => (_jsxs("svg", { viewBox: "0 0 24 24", width: "20", height: "20", fill: "none", "aria-hidden": "true", children: [_jsx("path", { d: "M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5z", stroke: "currentColor", strokeWidth: "2", strokeLinejoin: "round" }), _jsx("path", { d: "M12 16a4 4 0 1 0 0-8 4 4 0 0 0 0 8z", stroke: "currentColor", strokeWidth: "2" }), _jsx("path", { d: "M17.5 6.5h.01", stroke: "currentColor", strokeWidth: "3", strokeLinecap: "round" })] }));
const TikTokIcon = () => (_jsxs("svg", { viewBox: "0 0 24 24", width: "20", height: "20", fill: "none", "aria-hidden": "true", children: [_jsx("path", { d: "M14 3v10.2a4.8 4.8 0 1 1-4-4.73", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" }), _jsx("path", { d: "M14 7c1.6 2.2 3.6 3.3 6 3.4", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round" })] }));
const SpotifyIcon = () => (_jsxs("svg", { viewBox: "0 0 24 24", width: "20", height: "20", fill: "none", "aria-hidden": "true", children: [_jsx("path", { d: "M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18z", stroke: "currentColor", strokeWidth: "2" }), _jsx("path", { d: "M7.6 10.2c3.6-1 7.2-.8 9.9.7", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round" }), _jsx("path", { d: "M8.2 13.3c2.9-.7 5.7-.5 7.8.6", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round" }), _jsx("path", { d: "M8.8 16.2c2.1-.5 4-.3 5.5.4", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round" })] }));
const YouTubeIcon = () => (_jsxs("svg", { viewBox: "0 0 24 24", width: "20", height: "20", fill: "none", "aria-hidden": "true", children: [_jsx("path", { d: "M21 12s0-3.2-.4-4.6a2.6 2.6 0 0 0-1.8-1.8C17.4 5 12 5 12 5s-5.4 0-6.8.6A2.6 2.6 0 0 0 3.4 7.4C3 8.8 3 12 3 12s0 3.2.4 4.6a2.6 2.6 0 0 0 1.8 1.8C6.6 19 12 19 12 19s5.4 0 6.8-.6a2.6 2.6 0 0 0 1.8-1.8c.4-1.4.4-4.6.4-4.6z", stroke: "currentColor", strokeWidth: "2", strokeLinejoin: "round" }), _jsx("path", { d: "M10 9.8v4.4l4-2.2-4-2.2z", fill: "currentColor", stroke: "none" })] }));
export default function Footer({ isActive = true }) {
    const [phase, setPhase] = useState("in");
    useEffect(() => {
        setPhase(isActive ? "in" : "out");
    }, [isActive]);
    const cls = "page " +
        (phase === "in"
            ? "animate__animated animate__slideInRight"
            : "animate__animated animate__slideOutLeft");
    return (_jsxs("section", { className: cls, style: { animationDuration: "650ms" }, id: "footer", children: [_jsx("div", { className: "about-bg", "aria-hidden": "true" }), _jsxs("div", { className: "about-content footerPage", children: [_jsx(Container, { className: "footerCenterWrap", children: _jsx("div", { className: "footerCenter", children: _jsxs("h2", { className: "about-title about-title-centered footerTitle", children: [_jsx("span", { className: "about-title-light footerWhite", children: "NOT JUST A LABEL." }), _jsx("br", {}), _jsx("span", { className: "about-us-animated", children: "A MOVEMENT." })] }) }) }), _jsx(Container, { fluid: true, className: "footerBottomFluid", children: _jsxs("div", { className: "footerBottomBar", children: [_jsxs("div", { className: "footerSocials", "aria-label": "Social links", children: [_jsx("a", { className: "footerSocial", href: "https://www.instagram.com/purplecrunchrecords?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw%3D%3D", target: "_blank", rel: "noopener noreferrer", children: _jsx(InstaIcon, {}) }), _jsx("a", { className: "footerSocial", href: "https://www.tiktok.com/@purplecrunchrecords?is_from_webapp=1&sender_device=pc", target: "_blank", rel: "noopener noreferrer", children: _jsx(TikTokIcon, {}) }), _jsx("a", { className: "footerSocial", href: "https://open.spotify.com/", target: "_blank", rel: "noopener noreferrer", children: _jsx(SpotifyIcon, {}) }), _jsx("a", { className: "footerSocial", href: "https://youtube.com/", target: "_blank", rel: "noopener noreferrer", children: _jsx(YouTubeIcon, {}) })] }), _jsxs("nav", { className: "footerLinks", "aria-label": "Footer links", children: [_jsx(Link, { className: "footerLink", to: "/cookies", children: "Cookie Policy" }), _jsx(Link, { className: "footerLink", to: "/privacy", children: "Privacy Policy" }), _jsx(Link, { className: "footerLink", to: "/terms", children: "Terms & Conditions" }), _jsx(Link, { className: "footerLink", to: "/impressum", children: "Impressum" })] })] }) })] })] }));
}
